package com.resiflow.entity;

public enum NotificationType {
    USER_REGISTRATION_PENDING,
    CAGNOTTE_PAYMENT_PENDING_ADMIN,
    SHARED_EXPENSE_PAYMENT_PENDING_ADMIN,
    PAYMENT_VALIDATED,
    EXPENSE_CREATED,
    CAGNOTTE_CORRECTION_CREATED,
    VOTE_CREATED,
    VOTE_CLOSED,
    VOTE_DELETED
}
