package com.resiflow.dto;

public enum ApiErrorCode {
    VALIDATION_ERROR,
    INVALID_CAPTCHA,
    INVALID_CREDENTIALS,
    PASSWORD_RESET_CODE_INVALID,
    PASSWORD_RESET_CODE_EXPIRED,
    PASSWORD_RESET_RATE_LIMITED,
    PASSWORD_RESET_SESSION_INVALID,
    ACCOUNT_PENDING,
    ACCOUNT_REJECTED,
    ACCOUNT_ARCHIVED,
    INVALID_RESIDENCE_CODE,
    EMAIL_ALREADY_USED,
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND
}
